name: ascariaAdminTools
version: '${version}'
author: Gamer_m2082
main: fr.gamer_m2082.ascariaadmin.AscariaAdminTools
api-version: 1.16

commands:
  help:
    usage: /help
    aliases:
      - aide
    permission: admin.use
    description: get list of plugin functionality

  admin:
    usage: /admin
    permission: admin.adminmodo
    description: set admin to admin mod
