name: ascariaAdminTools
version: '${version}'
author: Gamer_m2082
main: fr.gamer_m2082.ascariaadmin.AscariaAdminTools
api-version: 1.16

commands:
  help:
    usage: /Ascaria
    aliases:
      - aideAscaria
    permission: admin.use
    description: get list of plugin functionality

  admin:
    usage: /admin
    permission: admin.adminmodo
    description: set admin to admin mod
  test:
    usage: /test
    permission: admin.devStrat
    description: Test if plugin start
